-- 041_brevethub_brevet_route_plan.sql
-- BrevetHub real RWGPS-backed ride plans: the persisted plan + its stops for a
-- cached calendar brevet.
--
-- rp_brevet_route_plan stores ONE real, RWGPS-derived ride plan per brevet
-- (rp_brevet_event), generated by the reused shared/rwgps.py engine
-- (build_ride_plan). rp_brevet_route_plan_stop holds its per-control rows. These
-- mirror Team Asha's proven ride_plan / ride_plan_stop column shape so the reused
-- engine's output persists verbatim — distances in MILES, speeds in MPH, elevation
-- in FEET (the /plan route converts to km / km-h at display time, never here).
--
-- Deliberately NOT the rp_ride_plan shell from migration 033 (that table is FK'd to
-- rp_ride, a live ride). A brevet route plan is keyed to a calendar brevet, so it
-- gets its own event-scoped table. UNIQUE(event_id) makes the warm/generate an
-- idempotent upsert (one real plan per brevet); slug is UNIQUE for a stable URL key.
--
-- Strictly additive + idempotent + rp_*-only, exactly like migrations
-- 033/035/036/037/038/039/040: guarded table creations plus guarded indexes,
-- referencing only rp_* tables. Applying (or re-applying) it cannot alter any Team
-- Asha table; code that predates the tables simply ignores them, so it is safe to
-- apply ahead of the code deploy.

-- --------------------------------------------------------------------------- --
-- rp_brevet_route_plan — one real RWGPS-derived plan per brevet.
--
-- club_id records which club owner generated the plan (nullable — the daily warm
-- cron generates club-less plans for national-feed events). Native units: the
-- column names say miles / ft / mph and hold exactly what build_ride_plan emits.
-- --------------------------------------------------------------------------- --
CREATE TABLE IF NOT EXISTS rp_brevet_route_plan (
    id                     SERIAL PRIMARY KEY,
    event_id               INTEGER NOT NULL REFERENCES rp_brevet_event(id),
    club_id                INTEGER REFERENCES rp_club(id),
    name                   TEXT NOT NULL,
    slug                   TEXT UNIQUE,
    total_distance_miles   NUMERIC,
    total_elevation_ft     INTEGER,
    rwgps_url              TEXT,
    rwgps_route_id         TEXT,
    distance_km            INTEGER,
    cutoff_hours           NUMERIC,
    start_time             TEXT,
    avg_moving_speed       NUMERIC,
    avg_elapsed_speed      NUMERIC,
    total_moving_time_min  INTEGER,
    total_elapsed_time_min INTEGER,
    total_break_time_min   INTEGER,
    overall_ft_per_mile    NUMERIC,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (event_id)
);

CREATE INDEX IF NOT EXISTS rp_brevet_route_plan_event_idx ON rp_brevet_route_plan (event_id);
CREATE INDEX IF NOT EXISTS rp_brevet_route_plan_club_idx ON rp_brevet_route_plan (club_id);

-- --------------------------------------------------------------------------- --
-- rp_brevet_route_plan_stop — the per-control rows of one route plan.
--
-- Mirrors Team Asha's ride_plan_stop: native miles / mph / feet, plus the derived
-- pacing/difficulty fields the engine computes (difficulty_score is a unit-agnostic
-- 0-10 score). ride_plan_id FK cascades conceptually with the parent plan; the
-- model deletes + re-inserts stops on every regenerate.
-- --------------------------------------------------------------------------- --
CREATE TABLE IF NOT EXISTS rp_brevet_route_plan_stop (
    id                SERIAL PRIMARY KEY,
    ride_plan_id      INTEGER NOT NULL REFERENCES rp_brevet_route_plan(id),
    stop_order        INTEGER NOT NULL,
    location          TEXT,
    stop_type         TEXT,
    distance_miles    NUMERIC,
    elevation_gain    INTEGER,
    segment_time_min  INTEGER,
    notes             TEXT,
    seg_dist          NUMERIC,
    ft_per_mi         NUMERIC,
    avg_speed         NUMERIC,
    cum_time_min      INTEGER,
    bookend_time_min  INTEGER,
    time_bank_min     INTEGER,
    difficulty_score  NUMERIC
);

CREATE INDEX IF NOT EXISTS rp_brevet_route_plan_stop_plan_idx
    ON rp_brevet_route_plan_stop (ride_plan_id, stop_order);
